global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    #    metrics_path: /metrics
    #scrape_interval: 30s
    #scrape_timeout: 25s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node1'
    #    metrics_path: /metrics
    #scrape_interval: 30s
    #scrape_timeout: 25s
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'node2'
    static_configs:
      - targets: ['localhost:9100']
